# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js-Jake Wrapper CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: ' 0 0 * * 0 '

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:rolling
      options: --privileged -it

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Jake (system)
      run: apt update && apt install node-jake -y
    - name: Build using Jake
      run: npm ci && jake
